apiVersion: v1
kind: Pod
metadata:
  name: log-test
spec:
  containers:
  - name: main-app
    image: busybox
    command: ['sh', '-c', 'i=0; while true; do echo "$i: $(date)" >> /var/log/myapp/log.txt; i=$((i+1)); sleep 1; done']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/myapp
  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'tail -n+1 -F /var/log/myapp/log.txt']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/myapp
  volumes:
  - name: shared-logs
    emptyDir: {}
